name: jaspr_demo
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_mappable: ^4.2.2
  http: ^1.2.2
  jaspr: ^0.16.0
  jaspr_router: ^0.6.0

dev_dependencies:
  build_runner: ^2.4.13
  jaspr_web_compilers: ^4.0.10
  jaspr_builder: ^0.16.0
  jaspr_lints: ^0.1.2
  lints: ^3.0.0
  dart_mappable_builder: ^4.2.3

jaspr:
  mode: server

